// morse-ai is the composition layer: it re-exports both halves so that a single
// import still gets you everything, and adds the pieces that genuinely need
// both — `Morse` itself, the protocol prompt, and the CLI.
export {
  Bus,
  BROADCAST,
  normalizeRecipients,
  newThreadId,
  unregistered,
  waitForInbox,
  waitForReply,
  openDb,
  dbPath,
  resetDb,
  type BusOptions,
  type Message,
  type MessageKind,
  type SendInput,
  type Registry,
  type Status,
  type AskResult,
  type AskOutcome,
  type WaitOptions,
} from "@morse-ai/bus";
export {
  resolveRoom,
  sanitizeRoom,
  FileRegistry,
  ONLINE_WINDOW_MS,
  isRunning,
  isValidAgentName,
  registryRoot,
  type Agent,
  type AgentStatus,
  type PublishInput,
} from "@morse-ai/registry";
export {
  isValidRoleName,
  isInside,
  loadRole,
  listRoles,
  parseRole,
  parseTomlRole,
  collectRoles,
  findRole,
  type RoleRejection,
  type RoleSearch,
  roleSearchPaths,
  roleSearchDirs,
  roleSearchReport,
  roleTemplate,
  type FieldMap,
  type ParseOptions,
  type RoleDefinition,
  type SearchDir,
  BUILTIN_PLUGINS,
  loadPlugins,
  pluginDirs,
  pluginsEnabled,
  expandDepth,
  type PluginDir,
  type PluginManifest,
  parseToml,
  tomlString,
  type TomlValue,
} from "@morse-ai/registry/discovery";
export { Morse, type RegisterInput } from "./morse.js";
export { buildPrompt, type PromptOptions } from "./prompt.js";
export { VERSION } from "./version.js";
export { buildHarnessArgs } from "./cli/main.js";
